master_data = {
    'run_category': [
        ("Bulk Dyed", 130),
        ("Bulk Yarn Dyed", 130),
        ("Bulk Full Bleach", 130),
        ("Bulk RFD", 130),
        ("Reprocess", "R02"),
        ("Lead cloth", "L01"),
        ("Yardage", 130),
        ("BL ", 130),
        ("RFS", 130),
        ("Process demand", "R05"),
        ("Trial Maintenance", 224),
        ("RFP Bulk", 130)
    ],
    'stop_category': [
        ("No StopType", 0),
        ("Machine cleaning", 201),
        ("Morning machine cleaning", 202),
        ("Fabric changeover", 203),
        ("Electrical Breakdown", 204),
        ("Mechanical Breakdown", 205),
        ("Utility Breakdown", 206),
        ("Preventive Maintenance", 207),
        ("Corrective Maintenance", 208),
        ("Low Air Pressure", 209),
        ("No Water", 210),
        ("Man power shortage", 211),
        ("Trolley/Batch Not Available", 212),
        ("Lead cloth stop", 213),
        ("No Program", 214),
        ("Chemical issue", 215),
        ("Pin Bar change", 216),
        ("Nip Test", 217),
        ("Quality fail due to mc", 218),
        ("Teflon finish cleaning", 219),
        ("Startup for Yardage", 220),
        ("Tank Not ok", 221),
        ("Quality fail due to process", 222),
        ("Radiator cleaning", 223),
        ("Oval Holing", 224),
        ("Power Cut", 225),
        ("Machine Tripping", 226),
        ("Oil Dropping", 227),
        ("Rubber Grinding/change", 228),
        ("Temperature Problem", 229),
        ("Planned Work", 230),
        ("Other Faults", 231),
        ("NO REASON SELECTED", 200)
    ],
    "operation_list": [
        (0, "NA"),
        (1, "FINISHNG"),
        (2, "WETSTRETCH"),
        (3, "DRYSTRETCH"),
        (4, "DRYING"),
        (5, "FOLDINGRTN"),
        (6, "FULLBLEACH"),
        (7, "POLYPAD"),
        (8, "BSTPAD"),
        (9, "STMPAD"),
        (10, "REPROCESS"),
        (11, "HEATSETT"),
        (12, "WETHEATSET"),
        (13, "THERMFIX"),
        (14, "WSTRETCHLA"),
        (15, "SANFOFINIS"),
        (16, "FELT"),
        (17, "DRYAIRO"),
        (18, "AIROBEAT"),
        (19, "CUREFINISH")
    ],

    'operators': [
        'RAJ KUMAR',
        'MITHLESH DUBEY',
        'NILESH KUMAR RAY',
        'DHARMENDRA KUMAR',
        'BITTU SINGH',
        'SURAJ KUMAR',
        'SUJEET KUMAR'
    ]
}
